settings:
  dataset:
    accumulate_batch_size: 1
    batch_size: 16
    eval_batch_scale: 1
    image_size:
    - 1280
    - 1280
    name: CropOrWeed2
    num_workers: 19
    seed: 4222
    stack2_images: true
    use_extra_class: 0
  loss:
    box_loss_weight: 0.05
    cls_loss_weight: 0.5
    obj_loss_weight: 1.0
    ota_loss: true
  lr_onecycle:
    base_momentum: 0.8
    div_factor: 80.0
    final_div_factor: 6500.0
    max_lr: 0.0005
    max_momentum: 0.937
    pct_start: 0.33
  lr_scheduler:
    milestone_multiplier: 0.1
    milestones:
    - 40
    - 50
    warmup_epochs: 1
    warmup_multiplier: 0.2
  mAP:
    iou_threshold: 0.7
    max_detections: 150
    min_confidence: 0.02
    nms_threshold: 0.02
  model:
    freeze: false
    name: yolov7-w6
    pretrained: true
  optimizer:
    learning_rate: 0.0005
    lr_scheduler: OneCycleLR
    name: SGD
    weight_decay: 0.0005
  trainer:
    ckpt_path: false
    deepspeed_config:
      train_batch_size: batch_size
      train_micro_batch_size_per_gpu: batch_size
      zero_allow_untested_optimizer: true
      zero_force_ds_cpu_optimizer: false
      zero_optimization:
        allgather_bucket_size: 500000000.0
        offload_optimizer:
          device: cpu
          pin_memory: true
        reduce_bucket_size: 500000000.0
        stage: 2
    max_epochs: 50
    precision: 16-mixed
    strategy: auto
